### ISSUE TITLE
Webview template crashes on start in Sketch 70.1 running on M1 Mac.

### ISSUE THREAD

**Issue by cyberalien** [skpm/with-webview#25]
Plug-in created with `skpm create my-plugin --template=skpm/with-webview` with sketch-module-web-view updated to version 3.4.4 crashes on start in Sketch 70.1 running on M1 Mac.

Original bug report: https://github.com/iconify/iconify-sketch/issues/16

**Comment by jink3** [comment]
Here's the crash log. 
[crash.log](https://github.com/skpm/with-webview/files/5609624/crash.log)

Iconify plugin has been somewhat problematic even before 2.0.2, right after I updated my intel mac to Big Sur I started having issues like the plugin just failing to load at all. Now that I'm on M1 mac on Big Sur, the latest update of Iconify seems to immediately crash Sketch upon launching the plugin. I can't say for sure if Iconify was stable on Sketch 70.0 running on M1 because I don't remember using it then.

**Comment by mathieudutour** [comment]
I don't have a M1 mac so can't repro. Happy to look at this issue if you are willing to sponsor one :smile:

**Comment by robintindale** [comment]
Also seeing this with the zeroheight plugin. We do have an M1 mac in the team so we may be able to kick off the debugging process if we get time.

**Comment by mathieudutour** [comment]
closing in favour of https://github.com/skpm/sketch-module-web-view/issues/168
